export const SAMPLE = 'SAMPLE';

export const GET_ALL_ROOM_SUCCESSFULLY = 'GET_ALL_ROOM_SUCCESSFULLY';
export const GET_ALL_ROOM_FAILED = 'GET_ALL_ROOM_FAILED';

export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';

export const ADD_NEW_ROOM_SUCCESSFULLY = 'ADD_NEW_ROOM_SUCCESSFULLY';
export const ADD_NEW_ROOM_FAILED = 'ADD_NEW_ROOM_FAILED';

export const ADD_NEW_DEVICE_SUCCESSFULLY = 'ADD_NEW_DEVICE_SUCCESSFULLY';
export const ADD_NEW_DEVICE_FAILED = 'ADD_NEW_DEVICE_FAILED';

export const LOADING_ROOM_LIST = 'LOADING_ROOM_LIST';

export const SET_LENGTH = 'SET_LENGTH';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_FLOORPLAN = 'SET_FLOORPLAN';
export const SET_LOADING = 'SET_LOADING';
export const SET_ROOM_NUM = 'SET_ROOM_NUM';
export const SET_FLOORPLAN_ID = 'SET_FLOORPLAN_ID';
