export const SAMPLE = 'SAMPLE';

export const GET_ALL_ROOM_SUCCESSFULLY = 'GET_ALL_ROOM_SUCCESSFULLY';
export const GET_ALL_ROOM_FAILED = 'GET_ALL_ROOM_FAILED';

export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';

export const ADD_NEW_ROOM_SUCCESSFULLY = 'ADD_NEW_ROOM_SUCCESSFULLY';
export const ADD_NEW_ROOM_FAILED = 'ADD_NEW_ROOM_FAILED';

export const ADD_NEW_DEVICE_SUCCESSFULLY = 'ADD_NEW_DEVICE_SUCCESSFULLY';
export const ADD_NEW_DEVICE_FAILED = 'ADD_NEW_DEVICE_FAILED';
